server:
  port : 9002
spring:
  application:
    name: tensquare-recuit #必须横杠来连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recuit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka
  instance:
    prefer‐ip‐address: true
